option(
  'cachedir',
  type: 'string',
  value: '',
  description: 'Default cache directory path'
)

option(
  'dependency_root',
  type: 'string',
  value: '',
  description: 'Prefix containing liblsmash and FFmpeg headers and libraries'
)

option(
  'vapoursynth_include',
  type: 'string',
  value: '',
  description: 'Path to the VapourSynth headers'
)
